#! /bin/sh

openrc default

mariadb-install-db

rc-service mariadb start

mariadbd --user=mysql \
        --datadir=/var/lib/mysql \
        --bootstrap << EOF
    FLUSH PRIVILEGES;
    CREATE USER IF NOT EXISTS root@localhost IDENTIFIED BY '$MARIADB_ADMIN_PASS';
    SET PASSWORD FOR root@localhost = PASSWORD('$MARIADB_ADMIN_PASS');
    GRANT ALL ON *.* TO root@localhost WITH GRANT OPTION;
    CREATE USER IF NOT EXISTS root@'%' IDENTIFIED BY '$MARIADB_ADMIN_PASS';
    SET PASSWORD FOR root@'%' = PASSWORD('$MARIADB_ADMIN_PASS');
    GRANT ALL ON *.* TO root@'%' WITH GRANT OPTION;
    CREATE DATABASE IF NOT EXISTS $MARIADB_DATABASE_NAME;
    CREATE USER IF NOT EXISTS $MARIADB_USER@'%' IDENTIFIED BY '$MARIADB_PASS';
    SET PASSWORD FOR $MARIADB_USER@'%' = PASSWORD('$MARIADB_PASS');
    GRANT ALL ON $MARIADB_DATABASE_NAME.* TO $MARIADB_USER@'%' WITH GRANT OPTION;
EOF

#cat << EOF > init.sql
#FLUSH PRIVILEGES;
#CREATE DATABASE $MARIADB_DATABASE_NAME;
#CREATE USER '$MARIADB_USER'@'%' IDENTIFIED by '$MARIADB_PASS';
#SET PASSWORD FOR $MARIADB_USER@'%' = PASSWORD('$MARIADB_PASS');
#GRANT ALL PRIVILEGES ON $MARIADB_DATABASE_NAME.* TO '$MARIADB_USER'@'%';
#ALTER USER 'root'@'localhost' IDENTIFIED BY '$MARIADB_ADMIN_PASS';
#FLUSH PRIVILEGES;
#EOF
#mysql -u root < init.sql

rc-service mariadb stop 

exec /usr/bin/mysqld 